// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/blog/[slug]": InferRoute<import("./src/app/blog/[slug]/routeType").RouteType>;
    "/projects/[slug]": InferRoute<import("./src/app/projects/[slug]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/about": StaticRoute;
    "/blog": StaticRoute;
    "/": StaticRoute;
    "/projects": StaticRoute;
  }
}
