import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Container from "../components/Container";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Carlo Taleon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className="bg-blue-50" maxWidth="7xl">
        <div>
          <h1 className="mb-5">Carlo Taleon Portfolio WIP</h1>
        </div>
        <Link href="https://www.figma.com/proto/3mchgUMnlaD0vim3jq0eAy/Portfolio-Project?node-id=103%3A7&scaling=min-zoom">
          <a
            target="_blank"
            className="text-6xl hover:bg-black hover:text-white transition"
          >
            Figma Prototype
          </a>
        </Link>
      </Container>
    </div>
  );
}
