import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Carlo Taleon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className="bg-yellow-50 w-full" style={{ height: "38rem" }}></div>
      <div className="bg-white w-full" style={{ height: "38rem" }}></div>
    </>
  );
}
